export const d1 = require('./images/1.png');
export const d2 = require('./images/2.png');
export const d3 = require('./images/3.png');
export const d4 = require('./images/4.png');
export const d5 = require('./images/5.png');
export const d6 = require('./images/6.png');
export const d7 = require('./images/7.png');
export const d8 = require('./images/8.png');
export const d9 = require('./images/9.png');
export const d10 = require('./images/10.png');
export const d11 = require('./images/11.png');
export const d12 = require('./images/12.png');
export const d13 = require('./images/13.png');
export const d14 = require('./images/14.png');
export const d16 = require('./images/15.png');
export const d17 = require('./images/16.png');
export const d15 = require('./images/17.png');
export const d18 = require('./images/18.png');
export const d19 = require('./images/19.png');
export const d20 = require('./images/20.png');
export const d21 = require('./images/21.png');
export const d22 = require('./images/22.png');
export const d23 = require('./images/23.png');
export const d24 = require('./images/24.png');
export const d25 = require('./images/25.png');
export const d26 = require('./images/26.png');
export const d27 = require('./images/27.png');
export const d28 = require('./images/28.png');
export const d29 = require('./images/29.png');
export const d30 = require('./images/30.png');
export const d31 = require('./images/31.png');
export const d32 = require('./images/32.png');
export const d33 = require('./images/33.png');
export const d34 = require('./images/34.png');
export const d35 = require('./images/35.png');
export const d36 = require('./images/36.png');
export const d37 = require('./images/37.png');
export const d38 = require('./images/38.png');
export const d39 = require('./images/39.png');
export const d40 = require('./images/40.png');
export const d41 = require('./images/41.png');
export const d42 = require('./images/42.png');
export const d43 = require('./images/43.png');
export const d44 = require('./images/44.png');
export const d45 = require('./images/45.png');
export const d46 = require('./images/46.png');
export const d47 = require('./images/47.png');
export const d48 = require('./images/48.png');
export const d49 = require('./images/49.png');
export const d50 = require('./images/50.png');
export const d51 = require('./images/51.png');
export const d52 = require('./images/52.png');
export const d53 = require('./images/53.png');
export const d54 = require('./images/54.png');
export const d55 = require('./images/55.png');
export const d56 = require('./images/56.png');
export const d57 = require('./images/57.png');
export const d58 = require('./images/58.png');
export const d59 = require('./images/59.png');
export const d60 = require('./images/60.png');

export const randomTime = () => {
   return (10 + Math.floor((Math.random() * 100) / 5)) * 1000;
};

export const pickRandom = () => {
   return Math.floor(Math.random() * 60) + 1;
};
